# Form implementation generated from reading ui file 'src\vista\app.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelTitulo = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTitulo.setGeometry(QtCore.QRect(50, 50, 300, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitulo.setFont(font)
        self.labelTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitulo.setObjectName("labelTitulo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName("menubar")
        self.menuCalculo_de_Areas = QtWidgets.QMenu(parent=self.menubar)
        self.menuCalculo_de_Areas.setObjectName("menuCalculo_de_Areas")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCirculo = QtGui.QAction(parent=MainWindow)
        self.actionCirculo.setObjectName("actionCirculo")
        self.actionTriangulo = QtGui.QAction(parent=MainWindow)
        self.actionTriangulo.setObjectName("actionTriangulo")
        self.actionRectangulo = QtGui.QAction(parent=MainWindow)
        self.actionRectangulo.setObjectName("actionRectangulo")
        self.actionCuadrado = QtGui.QAction(parent=MainWindow)
        self.actionCuadrado.setObjectName("actionCuadrado")
        self.actionSalir = QtGui.QAction(parent=MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.menuCalculo_de_Areas.addAction(self.actionCirculo)
        self.menuCalculo_de_Areas.addAction(self.actionTriangulo)
        self.menuCalculo_de_Areas.addAction(self.actionRectangulo)
        self.menuCalculo_de_Areas.addAction(self.actionCuadrado)
        self.menubar.addAction(self.menuCalculo_de_Areas.menuAction())
        self.menubar.addAction(self.actionSalir)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora de Áreas"))
        self.labelTitulo.setText(_translate("MainWindow", "Calculadora de Áreas\n"
"Seleccione una figura del menú"))
        self.menuCalculo_de_Areas.setTitle(_translate("MainWindow", "&Cálculo de Áreas"))
        self.actionCirculo.setText(_translate("MainWindow", "&Círculo"))
        self.actionCirculo.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionTriangulo.setText(_translate("MainWindow", "&Triángulo"))
        self.actionTriangulo.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionRectangulo.setText(_translate("MainWindow", "&Rectángulo"))
        self.actionRectangulo.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionCuadrado.setText(_translate("MainWindow", "C&uadrado"))
        self.actionCuadrado.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionSalir.setText(_translate("MainWindow", "&Salir"))
        self.actionSalir.setShortcut(_translate("MainWindow", "Ctrl+Q"))
